language: node_js
node_js:
- node
jobs:
  include:
  - stage: test
    script: npm test
  - stage: lint
    script: npm run lint
  - stage: release
    if: type = push AND tag IS present
    install: true
    script: skip
    deploy:
      provider: npm
      email: elviswolcott@gmail.com
      api_key:
        secure: lNF+2FSZU0EsH9jerhWYbZT9dKiO1Kfz2NPuA/mSk5UkVTOQC+8A9ufkyF9kkwcDgBXvxsUcI0OM9C0wQatE2DIqGNOo9YzkUfF7zcxC63Nb878alp6tcVDflRIP/a5X3la5loq7uxEPD/8JJICt54Y6OJBW8GlZ8+ZvtlZzba8ZIW3G6JEBh1mXH1ZGBCbRuVw7kLaFe7E1VEgYHLIcAm6bVB8DvK4Kqtjx4karv8y8+u2NMV+qj9QkrqHpqTfcwNqbQXmKJIcdX42tC4f8ImweeE4Jvv0s6bg76FTuOR1O4yTp+8gUplZqdP6JWJj3OS3RaooYrrUqN4d7ZJ5z8u3yvzu8LrVfQmruza+TkixNLKzQfGwAxPtt/Rc/VWyG3aJNcz8AkAyufnLX/OOT6XR2oBSZtB9Dhk7OcZeKu9ZpLg9J8Z73weWJipCYsVefnxEVg01fzqrfeKBC1jBeuOEe3IEcMkczpxDAp4o5wpyc7KaHdcWTFzasOIWjb/XNgQ6JRylIDD+Zg9HiQjzKodE3hDELMypRHVBD2a9sdxO2pNIpBSvf7LAJAz5okxl1+y2S9Hn6+aNEL0aMMP0pxBi4A28vVc4oSVHy4Uz1mKaJSj1z6BWxZ0N06CKAoDe8GjWi3ycimRvU86nGIUOWJ/eBVNRuqNdFmRW4+zVs6WU=
      on:
        tags: true
        repo: elviswolcott/remark-admonitions
        branch: master
stages:
- test
- lint
- release
deploy:
  provider: npm
  email: elviswolcott@gmail.com
  api_key:
    secure: TtagjPvj4tyrRRNOHyNXPX5pp5qRVYZz3jl/Lj+/e99cdGhazGp2lqULenhCbG9Cl3HOVU7iC7R2SrGInVXjsP1glQKj7eTeAHQZDsEEiBKS2hgB0EtjxGAWVgSnxGE4y6oEnHxQVzNQBBESD4DNfAoOKuGrb5Ba6VLX7WS7WvZ+AyQOZqeQTlNOCGfixFIfnPj/GC5wAt8L3REJsLV7vQGijUB9G6urci0mUEqt24Q6bw28rhyMEf9UFPp9zgJCOmUE+niUCSLXLNo+mbR0XuUmBXfs99JLmMmqU6EHF2c0BS1uhjEsOfu+AwGdSgHN5hSQk1Va8kvZy/vGuLAkXR8lk9PBZWrvzZyc64dBkQgrD/nosilfwBGNAGz64OtG8L7+ZQFWiZoQ8YORmRdelHobfVCel+Q8C2KydTmxHRsINMH+SEsb105la6Zd5jleYeaGsno5RPieSmrXhodPxY7RzJeZbJp9Y7/L3HQOZcyn99wkxEzbWj0ivB2QuDrCpsA1SM91Vf7v5A760d3bO2xLJfCWFqciMmcbJlUyroampMrO0rj+fknJABjJOcHrKkkgugiWGfWlDtffN0PGBuinw3dpCJsYIGHwWQ/BivaznRmeeNd0eZuejhBF20B5CsOibemamA/5LkCL4pXzu+dLjyat7v4HDgZaxuPrCW0=
  on:
    tags: true
    repo: elviswolcott/remark-admonitions
