language: node_js
node_js:
- node
jobs:
  include:
  - stage: test
    script: npm test
  - stage: lint
    script: npm run lint
    # because the package isn't being compiled in any way, install and script are skipped
  - stage: release
    if: type = push AND tag IS present
    install: true
    script: skip
    deploy:
      provider: npm
      email: elviswolcott@gmail.com
      api_key:
        secure: hqgX+7KEkEkdWlSjtjDozXK9utQfGd7SB1X3uuSRV89smcM5UmAL/UbLl+ziJWPwR/nr9jk5prVTJxQgKIimR4y7s1144u5nc2C51k+PxhRtTNnF+VdHggt1SQUr5IZfBYeWq+z6TeJEsTXc1lhO/rdbB8+/MPdGXnOk6IkLQJaQglzxPzmLWUD4lHUUBr5KvQ4S+DfMSZuvuJ8X9JeuTbXpHwFpa6dG/TvxoQivTIMqa0Apm8OR+8IBXTt844F075pUgurRh/rFhUQpIEjRxH+czz1EnPVNfviIsqnHbGOW46DrLXSUIkkVx76OluC9B7JF9FF/TISycpN/d2F7G9rkxq7/zP18d/fQpm7UNImdE6uJNoiUnx59B6s/Nkyj7uMe2H3PRO1Mrvm5bSXTltDVTBFTyBvUqi2eGUqMyEOpojjZiuTvkTlBV6NwioDch/cx1thKr92M6ZQIQPcVRH67nSSda27FS1UPQYJ3118GIR76oGDIfF9g5B9lGwYEwlk/xl5mP70fs+M/L1tU2NhQXFMIGS4TEeAvDE2HTbMNItQcYaMY/K2tNLgeK/DYOWZ83Nbi0sGscA10db6nW+BwpgtB4CDXmxfP4oRCIaNHnojWFcQkshkiZCxugb4cyHUm5SfZC7AHDExfpehLDs8rzDhgN4l6LrfuOX9FQiE=
      on:
        tags: true
        repo: elviswolcott/remark-admonitions
        branch: master

stages:
- test
- lint
- release